### ISSUE TITLE
Error in generating condensed tree plot

### ISSUE THREAD

**Issue by s0j0urn** [lmcinnes/hdbscan#16]
Hi,

I am getting the following error while generating clusterer.condensed_tree_.plot()

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-18-1ce791da72a0> in <module>()
    ----> 1 clusterer.condensed_tree_.plot()
    
    /home/intel/anaconda2/lib/python2.7/site-packages/hdbscan/plots.pyc in plot(self, leaf_separation, cmap, select_clusters, label_clusters, axis, colorbar, log_size)
        272                 'Use get_plot_data to calculate the relevant data without plotting.')
        273 
    --> 274         plot_data = self.get_plot_data(leaf_separation=leaf_separation, log_size=log_size)
        275 
        276         if cmap != 'none':
    
    /home/intel/anaconda2/lib/python2.7/site-packages/hdbscan/plots.pyc in get_plot_data(self, leaf_separation, log_size)
        112 
        113         for cluster in range(last_leaf, root - 1, -1):
    --> 114             split = self._raw_tree[['child', 'lambda']]
        115             split = split[(self._raw_tree['parent'] == cluster) &
        116                           (self._raw_tree['child_size'] > 1)]
    
    /home/intel/anaconda2/lib/python2.7/site-packages/numpy/core/_internal.pyc in _index_fields(ary, names)
        321     for name in names:
        322         if name not in dt.fields:
    --> 323             raise ValueError("no field of name %s" % name)
        324 
        325     formats = [dt.fields[name][0] for name in names]
    
    ValueError: no field of name lambda

Also I was wondering if it is possible to extract all clusters from condensed tree corresponding to all lambda levels with the ids of points belonging to them or representing parent child relationship between them. I have already tried      clusterer.condensed_tree_.to_pandas()   but I was not able to understand its output. I ran the test for 50 points and it generated 54 rows in the dataframe.  That will mean 4 clusters if I am understanding it correctly. 

But in these 4 clusters as well there should be a parent child relationship in a hierarchy. How to establish that ? Also, how to associate actual points data with the dataframe generated.

Sorry, If my post is not clear. Let me know and I'll provide more details if needed.

**Comment by lmcinnes** [comment]
The first part is an honest bug; I need to update plots to match some changes made to get around numpy's slower structured array access. I'll get to that very soon.

The second question is a little trickier. The condensed tree in pandas format does contain all the information you want, just not necessarily in a very easy to access way. Each row of the data frame is an edge in the tree (viewing the tree as a graph). It lists the parent node, the child node, the lambda value at which this split occurs, and the size of the child node created (number of points in the child cluster). Clusters and points are all numbered; points have id numbers in the range 0-num_points, and any id number greater than the number of points in your dataset is a cluster. For any cluster in the tree you can find the points in it by doing a breadth first search on this (directed) graph and recording all the points you encounter. The parent/child relationships between clusters are explicitly recorded in the edges.

Anyway, having a nicer representation available in terms of the structure/form you are suggesting is probably useful so that'll go on the to do list.
