### ISSUE TITLE
conda install issue

### ISSUE THREAD

**Issue by ianozsvald** [lmcinnes/hdbscan#20]
Hi there. I'm using `hdbscan` via a `pip install hdbscan` successfully in a Linux 64 bit Anaconda Python 3.4 environment (cheers!).

However - if I try to use the `conda` installer against what I think is your channel, I get a problem:
```
$ conda install -c https://conda.anaconda.org/lmcinnes hdbscan
<success>
...
$ ipython
...
In [1]: import hdbscan
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3f1c79fb1b69> in <module>()
----> 1 import hdbscan

/home/ian/anaconda/envs/scratch/lib/python3.4/site-packages/hdbscan/__init__.py in <module>()
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage

/home/ian/anaconda/envs/scratch/lib/python3.4/site-packages/hdbscan/hdbscan_.py in <module>()
     27     check_array = check_arrays
     28 
---> 29 from ._hdbscan_linkage import (single_linkage,
     30                                mst_linkage_core,
     31                                mst_linkage_core_pdist,

ImportError: /home/ian/anaconda/envs/scratch/lib/python3.4/site-packages/hdbscan/_hdbscan_linkage.so: invalid ELF header
```

I've switched back to the `pip` version, I'd love to keep this in `conda` if possible.

**Comment by lmcinnes** [comment]
We have some issues with the conda build process right now. Currently it only works for MacOS, as that's what I'm generally building on. We need to get some infrastructure to build on different systems -- since we have cython code the `conda convert` for different platforms doesn't actually suffice. When I get some time I'll see about getting some time on amazon or something to do builds there on different systems.

**Comment by lmcinnes** [comment]
We are now on conda-forge so you can do

    conda install -c conda-forge hdbscan

and all should be good!
